// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXmQIXTZ22oPXr0nTnY-CeHKBHZW7lxwU',
    appId: '1:117694919344:web:9861b8be1fbb6a6ba0c175',
    messagingSenderId: '117694919344',
    projectId: 'shop-me-710ab',
    authDomain: 'shop-me-710ab.firebaseapp.com',
    storageBucket: 'shop-me-710ab.appspot.com',
    measurementId: 'G-H3KBSZ5EZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZLKFPYV4nwWJlLQ6M3ER5kfdh3Toyazk',
    appId: '1:117694919344:android:b331252b6f9cb7a1a0c175',
    messagingSenderId: '117694919344',
    projectId: 'shop-me-710ab',
    storageBucket: 'shop-me-710ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_n7QG88znfBkXRUqOvaANgRQGutlXzJQ',
    appId: '1:117694919344:ios:508448ff45871e7ea0c175',
    messagingSenderId: '117694919344',
    projectId: 'shop-me-710ab',
    storageBucket: 'shop-me-710ab.appspot.com',
    iosClientId: '117694919344-kkmij8q38hmoa7occ8u1dqogjh7t64kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_n7QG88znfBkXRUqOvaANgRQGutlXzJQ',
    appId: '1:117694919344:ios:508448ff45871e7ea0c175',
    messagingSenderId: '117694919344',
    projectId: 'shop-me-710ab',
    storageBucket: 'shop-me-710ab.appspot.com',
    iosClientId: '117694919344-kkmij8q38hmoa7occ8u1dqogjh7t64kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopMe',
  );
}
